### ISSUE TITLE
Could you provide clarification on whether PAD requires labels or not during training? 

### ISSUE THREAD

**Issue by ilwoof** [sheoyon-jhin/PAD#1]
Hi authors,

When comparing the code with your paper, I am confused about your proposed approach PAD. Specifically, I am confused about whether PAD requires the use of labels during the training phase or not.  Upon reviewing line 465 of pad.py, it appears that batch labels were utilized during training. Could you provide clarification on whether PAD requires labels during training? Thanks a lot!

Regards,

Craig

**Comment by sheoyon-jhin** [comment]
Yes, we use labels during the training phase.  batch_y means present labels of data.
