### ISSUE TITLE
unable to reproduce the result

### ISSUE THREAD

**Issue by Isabellalli** [sheoyon-jhin/PAD#4]
When I tried to reproduce your experiment using the WADI dataset, the results were quite different from what you reported in your paper, SEPECIALLY for the normal AD task. Could you please provide details on how you specifically processed the WADI dataset？OR could you provide the detailed setting? 

<img width="580" alt="截屏2024-08-30 21 43 48" src="https://github.com/user-attachments/assets/a6d436c1-0de6-4eb6-95a8-2ebcec50d8ee">

**Comment by sheoyon-jhin** [comment]
Hi, 
I just found that this code is not finalized version.. 
Could you wait for it? 
Thank you and sorry for this. 
Best regards, 
Sheo yon
